import os
import datetime
from google import genai
from google.genai import types

# ==============================
# 1. CONFIGURATION & SECURITY
# ==============================

API_KEY = os.environ.get("GEMINI_API_KEY")
if not API_KEY:
    raise ValueError("🚨 GEMINI_API_KEY environment variable not found! Check your GitHub Secrets.")

MODEL_NAME = "gemini-2.5-flash"  
client = genai.Client(api_key=API_KEY)

# Using strict configuration to handle the massive prompt without hallucinating
base_config = types.GenerateContentConfig(
    temperature=0.2,            
    top_p=0.9,
    top_k=40,
    max_output_tokens=8192,
    tools=[{'google_search': {}}]
)

# ==============================
# 2. DATE & TIME SETUP (IST)
# ==============================

ist_timezone = datetime.timezone(datetime.timedelta(hours=5, minutes=30))
now = datetime.datetime.now(ist_timezone)

report_id_date = now.strftime("%Y%m%d")
full_date_str = now.strftime("%-d %B %Y")
time_str = now.strftime("%H:%M")

# ==============================
# 3. UNCUT MAIN REPORT PROMPT
# ==============================

main_prompt = f"""
Act as a Senior Global Intelligence Analyst.

Produce a structured, neutral, fact-based daily intelligence briefing.
Focus only on the most important and trending developments from the last 24 hours.
Avoid repetition. Do not speculate.

Include when relevant:
What happened | When | Where | Who | Why | Immediate impact | Policy implications.

Output strictly in Markdown.

# Global Daily Intelligence Briefing

Report ID: GN-{report_id_date}
Full Date: {full_date_str}
Report Time Reference: {time_str} (UTC+05:30)
Region Coverage: Global | India | MENA | Technology | Economy
Report Generated By: Gemini Pro 3.1 By Google LLC

---

## SECTION 1 — Global Pulse
(Trending global geopolitics, wars, markets, sports, achievements, summits)

## SECTION 2 — Gulf & MENA Region
(Major MENA developments only)

## SECTION 3 — Technology
(AI tools released today, major tech shifts)

## SECTION 4 — Global Business & Industry
(Business announcements, CEO statements, M&A)

## SECTION 5 — Global Security & Terrorism Monitor
(Terror, cyber warfare, espionage)

## SECTION 6 — Global Economy
(Stock markets, inflation, central banks, commodities)

## SECTION 7 — India National
(Top national developments of last 24 hours)

## SECTION 8 — Telangana State Updates
(All major Telangana news)

## SECTION 9 — Andhra Pradesh State Updates
(All major Andhra news)

## SECTION 11 — This Day in History (India)
(3–5 historical events)

## SECTION 12 — Deep Analysis
(One major story explained in depth)

## SECTION 13 — Complete Summary
(One-line takeaway per section)

-- END MAIN REPORT --
"""

# ==============================
# 4. GOLD VERIFICATION PROMPT
# ==============================

gold_prompt = f"""
Verify today's gold rates for Hyderabad from Goodreturns.in.

STRICT RULES:
- Use Goodreturns.in Hyderabad page as PRIMARY source.
- Date must match {full_date_str}.
- Do not estimate.
- If unavailable, clearly state unavailable.

Provide output exactly in this format:

## SECTION 10 — Gold Rates (Hyderabad Market)

- **24 Carat (10g):** ₹
- **22 Carat (10g):** ₹
- **Change from Yesterday:**
- **Reason for Movement:**
- **Source:** Goodreturns.in
"""

# ==============================
# 5. GENERATION FUNCTION
# ==============================

def generate_content(prompt):
    response = client.models.generate_content(
        model=MODEL_NAME,
        contents=prompt,
        config=base_config
    )
    return response.text

# ==============================
# 6. EXECUTION: BUILD REPORTS
# ==============================

try:
    print("⏳ Generating Main Intelligence Report...")
    main_report = generate_content(main_prompt)
except Exception as e:
    print(f"❌ Error generating main report: {e}")
    main_report = "Main report generation failed."

try:
    print("⏳ Verifying Hyderabad Gold Rates...")
    gold_section = generate_content(gold_prompt)
except Exception as e:
    print(f"❌ Gold verification failed: {e}")
    gold_section = "## SECTION 10 — Gold Rates (Hyderabad Market)\nGold rate verification failed."

# ==============================
# 7. MERGE REPORT (Safely Inserting Section 10)
# ==============================

if "## SECTION 11" in main_report:
    final_report = main_report.replace("## SECTION 11", f"{gold_section}\n\n## SECTION 11")
else:
    final_report = main_report + "\n\n" + gold_section

# Save the full Markdown Archive
filename = f"Global_Intelligence_Report_{report_id_date}.md"
with open(filename, "w", encoding="utf-8") as f:
    f.write(final_report)
print(f"✅ Final Markdown saved as: {filename}")

# ==============================
# 8. TELUGU EMAIL TRANSLATION
# ==============================

print("⏳ Generating Telugu Email Summary...")
email_summary_path = "email_body.html"

# Safely extract SECTION 13 for the email summary
summary_start = main_report.find("## SECTION 13")

if summary_start != -1:
    english_summary = main_report[summary_start:].strip()
    
    telugu_prompt = f"Translate this news summary into professional Telugu (Vaarthalu style). Keep the bullet points:\n\n{english_summary}"
    
    try:
        telugu_text = generate_content(telugu_prompt)
        html_list = telugu_text.replace("- **", "<li><b>").replace("**:", "</b>:").replace("\n- ", "</li><li>")
        
        final_html = f"""
        <html>
          <body style="font-family: 'Gautami', Arial, sans-serif; line-height: 1.8; color: #333; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
            <h2 style="color: #d32f2f; border-bottom: 2px solid #d32f2f; padding-bottom: 10px;"> ఈరోజు ముఖ్యాంశాలు</h2>
            <p style="color: #666; font-weight: bold;">తేదీ: {full_date_str}</p>
            <ul style="padding-left: 20px;">
              {html_list}
            </ul>
            <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
            <p style="font-size: 11px; color: #999; text-align: center;">జెమిని తెలుగు వార్తా వాహిని ద్వారా రూపొందించబడింది</p>
          </body>
        </html>
        """
    except Exception as e:
        print(f"Telugu translation failed: {e}")
        final_html = f"<html><body><p>News Briefing for {full_date_str} is ready in GitHub.</p></body></html>"
else:
    final_html = f"<html><body><p>News Briefing for {full_date_str} is ready in GitHub.</p></body></html>"

with open(email_summary_path, "w", encoding="utf-8") as f:
    f.write(final_html)
print("Telugu Email HTML saved successfully!")
